### ISSUE TITLE
chartmogul.Plan.all() doesn't work

### ISSUE THREAD

**Issue by tisdall** [chartmogul/chartmogul-python#79] opened 2023-07-13 14:49 UTC
I'm trying [Plan.all the example straight from the docs](https://dev.chartmogul.com/reference/list-plans):
```python
>>> chartmogul.__version__
'3.1.2'
>>> result = chartmogul.Plan.all(config, per_page=3).get()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "venv/lib/python3.9/site-packages/promise/promise.py", line 512, in get
    return self._target_settled_value(_raise=True)
  File "venv/lib/python3.9/site-packages/promise/promise.py", line 516, in _target_settled_value
    return self._target()._settled_value(_raise)
  File "venv/lib/python3.9/site-packages/promise/promise.py", line 226, in _settled_value
    reraise(type(raise_val), raise_val, self._traceback)
  File "venv/lib/python3.9/site-packages/six.py", line 719, in reraise
    raise value
  File "venv/lib/python3.9/site-packages/promise/promise.py", line 87, in try_catch
    return (handler(*args, **kwargs), None)
  File "venv/lib/python3.9/site-packages/chartmogul/errors.py", line 21, in annotateHTTPError
    raise err
  File "venv/lib/python3.9/site-packages/promise/promise.py", line 87, in try_catch
    return (handler(*args, **kwargs), None)
  File "venv/lib/python3.9/site-packages/chartmogul/resource.py", line 111, in _load
    return cls._loadJSON(jsonObj)
  File "venv/lib/python3.9/site-packages/chartmogul/resource.py", line 117, in _loadJSON
    return cls._many(
TypeError: <lambda>() got an unexpected keyword argument 'has_more'
```

Seems to happen regardless of whether there actually is more than a single page of data or not.  I added querystring terms to just fetch a single plan and it raises the same error.

However, a similar query on another paginated endpoint works fine:
```python
result = chartmogul.Invoice.all(config, per_page=3).get()
```

**Comment by pkopac** [comment] 2023-07-14 07:38
Hi @tisdall, thanks for reporting! It seems to be a recent regression, we'll look into it right away!

**Comment by swember** [comment] 2023-07-14 10:45
Hi @tisdall, the fix has been deployed and this should work now, sorry for the long resolve of the issue.

**Comment by tisdall** [comment] 2023-07-14 11:54
Thanks for the incredibly fast turn-around!  

I see you just removed the `"has_more"` on the JSON response.  I don't see `marshmallow` in the trace but I wonder if the code should be changed to simply ignore unknown keys in the response so future changes are less likely to break this library?  A coworker was using the Ruby library and didn't encounter any error.

**Comment by swember** [comment] 2023-07-14 12:51
Yes, we use `marshmallow` to process internal objects in JSON. `has_more` is on a higher level, that's why it broke processing. We'll work on that to avoid it in future. Thank you for the note about Ruby library.

Closing this as the issue has been resolved.

**Closed by swember** 2023-07-14 12:51 UTC
