### ISSUE TITLE
Invoice api returns undocumented field (has_more) and breaks _many named tuple mapping. 

### ISSUE THREAD

**Issue by dalbello** [chartmogul/chartmogul-python#83] opened 2023-09-20 04:08 UTC
Hi @swember and @pkopac, I'm opening a new issue as #80 is now closed.  

I'm seeing this issue too. Are you sure this fix was deployed? Or maybe this bug has made its way back into production again?

**Code**:
invoices = chartmogul.Invoice.all(config,external_id=order_id).get(); 

**Error**:
TypeError: <lambda>() got an unexpected keyword argument 'has_more'

I've checked the API and it is returning a field called **has_more** on the JSON payload, but it seems that the invoice schema doesn't handle this. 

If anyone is experiencing this issue, changing **invoice.py** 
` _many = namedtuple('Invoices', [_root_key, "current_page", "total_pages", "customer_uuid"])` 
to  
`_many = namedtuple('Invoices', [_root_key, "current_page", "total_pages", "has_more", "customer_uuid"])` 
fixes the issue.

**Comment by kmossco** [comment] 2023-09-20 12:52
Hey @dalbello, thank you for reporting this. We are currently in the process of changing the pagination in the library but that will come with the next major version for which we have a PR open already [here](https://github.com/chartmogul/chartmogul-python/pull/81). But in the mean time, I tried reproducing this with the current latest released version and it worked for me:

```python
chartmogul.Invoice.all(config, per_page=1).get()
Invoices(invoices=[<Invoice{currency='EUR', customer_uuid='cus_1245b3b0-2c82-11ee-aef1-93c289e29cdb', date=datetime.datetime(2023, 7, 26, 23, 0, tzinfo=datetime.timezone.utc), due_date=datetime.datetime(2023, 7, 26, 23, 0, tzinfo=datetime.timezone.utc), external_id='1', line_items=[<LineItem{account_code='', amount_in_cents=11100, description=None, discount_amount_in_cents=0, discount_code='', discount_description=None, event_order=None, external_id=None, plan_uuid=None, quantity=1, tax_amount_in_cents=0, transaction_fees_currency=None, transaction_fees_in_cents=0, type='one_time', uuid='li_5d8424c3-4089-4e7f-a7b3-67f38fb35de9'}>], transactions=[<Transaction{amount_in_cents=11100, date=datetime.datetime(2023, 7, 26, 23, 0, tzinfo=datetime.timezone.utc), external_id=None, result='successful', type='payment', uuid='tr_49973871-fc39-4fd9-8c68-6c0721b9543e'}>, <Transaction{amount_in_cents=11100, date=datetime.datetime(2023, 7, 26, 23, 0, tzinfo=datetime.timezone.utc), external_id=None, result='successful', type='refund', uuid='tr_15dcd1f9-6d0f-4791-bd68-2829007eb74e'}>], uuid='inv_c183cce8-a9f4-4992-b2d0-f42e16309866'}>], current_page=1, total_pages=24, customer_uuid=None)
```

Can you please confirm what version of the library you are using and whether you are sending a custom user agent with your requests?

**Comment by dalbello** [comment] 2023-09-21 01:28
@kmossco I'm using 1.5.0, but I tried using 3.1.2 with the same results. Keep in mind that in my call I'm not using per_page, and just using external_id, I think the issue might just be happening when there are no invoices returning. It seems that "has_more" is only showing up on an empty return.

**Comment by swember** [comment] 2023-09-21 16:46
Hello @kmossco, sorry about the inconvenience. The API itself should return `has_more` and this is an expected behaviour. We only restrict it for libraries by sending a certain `User-Agent` header in the request from the lib. The 1.5.0 is a very old version of the library which does not send the correct `User-Agent` header. On 3.1.2 I was not able to reproduce the issue. Here is my result:
```Python
chartmogul.Invoice.all(config, external_id="non_existing_id").get()
Invoices(invoices=[], current_page=1, total_pages=0, customer_uuid=None)
Could you please try one more time with the latest version?

**Comment by dalbello** [comment] 2023-09-22 20:56
Hi @swember,

Having to change code that has been running smoothly for over a year is far from ideal. This is a legacy platform running python 3.7, so your dependencies will create a lot more work to get this upgraded. I'll try again with the latest version as you suggested, as my test was to validate if the field was still returning on a separate file. However, I would like to mention that I wasn't informed about any breaking changes. If the API is going to deploy breaking changes, a new version like V2 would be a more appropriate approach to ensure backward compatibility.

**Comment by kmossco** [comment] 2023-09-26 12:14
@dalbello thank you for giving us a bit more context into how you are using this library. The idea was not to change the existing functionality for customers using it, so with that in mind we adapted our API to parse the library User Agent of the libraries so that we can return the current behaviour if someone is using an older library version. The problem you faced is that the version you are using is not sending us the custom User Agent more recent versions of the library are sending, but this issue should now be resolved on the server side, can you confirm?

In the mean time, we will push an update to the current library version so that if any regression happens on our end it won't break the requests. In the near future we will have a new major release to remove the old pagination and support only cursor, and you then can upgrade at your convenience.

**Comment by dalbello** [comment] 2023-09-27 00:58
@kmossco Just to clarify, should version 1.5 now work again in production? Right now I have a fork of the library running where I changed invoice.py to handle the has_more field. So just want to clarify before I revert back to 1.5 and see how it goes.

**Comment by kmossco** [comment] 2023-09-27 12:17
@dalbello that is correct, we made some changes on the server side to allow it to work without breaking changes. Can you retry and see if that works for you? In the mean time, we will be releasing soon a bugfix to avoid regressions as `v3.1.3`.

**Comment by dalbello** [comment] 2023-09-28 00:25
Hi @kmossco I just tried, and it didn't work. Still same error and has_more still comes back as well. See screenshot and error generated.

```
return cls._many(cls._schema.load(jsonObj[cls._root_key], many=True).data,
TypeError: <lambda>() got an unexpected keyword argument 'has_more'
```
![Screenshot_2023-09-28_at_10_18_38 am](https://github.com/chartmogul/chartmogul-python/assets/896907/f8c0b349-bf06-4f11-ae6d-f945c94b416b)

**Comment by kmossco** [comment] 2023-09-28 13:22
Sorry for the inconvenience @dalbello, we tried to reproduce it on our end but we were not able to. Can you confirm what version of the Python library you are using? Was that test through your fork, or was that through cURL using a GUI tool only?

We have a branch open for a bugfix on the library to avoid any regression [here](https://github.com/chartmogul/chartmogul-python/pull/84), maybe you can give that a try in the meantime? The version you are currently using had some issues and we released several new endpoints and fixes since then. I am just resolving a couple of issues in the tests, and we should release it very soon after some internal test to ensure we can't reproduce the error you are seeing.

**Comment by dalbello** [comment] 2023-10-01 23:32
@kmossco the screenshot I sent was captured via Proxyman when I run the application locally using branches 1.5.0 and 1.4.0. The application is running on a Heroku container on python 3.7 (remote) and 3.9 (local). What did you expect as a behaviour? Are you still returning certain fields depending on the agent header? If that's the case wouldn't it be better if these are only returned if  the new library header is posted?

**Comment by kmossco** [comment] 2023-10-02 15:03
@dalbello thanks for confirming that, the behaviour should be that you do not get the mixed pagination. As in, if you send a `page` query param you should not get `has_more` nor `cursor`. But because we didn't want to break customers that use cURL or Python request libraries directly, we have to use the custom User-Agent headers that the libraries send to determine what type of pagination to show by default when no query param is sent. The problem is that the version of the library you are using does not have that header being sent with it, so you are getting the new version as our server assume you are not using one of our libraries.

In order to make the upgrade path smoother for you we are releasing very soon a new version `v1.5.1` that will send the User-Agent header and also supports both types of pagination based on this PR: https://github.com/chartmogul/chartmogul-python/pull/85. This way as soon as you upgrade to it you won't have this issue anymore. Hope this helps!

**Comment by kmossco** [comment] 2023-10-02 18:06
@dalbello we just released the version `1.5.1` and I tested in a new Python application to make sure everything works correctly and the behaviour seems to be correct now:

```
➜  python-test python python.py
Invoices(invoices=[], current_page=1, total_pages=0, cursor=None, has_more=None, customer_uuid=None)
```

Can you test on your side and see if this now works for you?

**Comment by dalbello** [comment] 2023-10-03 00:39
@kmossco the issue was probably because I was not sending "per_page". Just the external id. 
I will try the 1.5.1 version tomorrow and let you know. I can't do it today, but thanks for looking into it. Obrigado! 👍

**Comment by kmossco** [comment] 2023-10-03 12:54
Sounds good, let us know if you bump into any other issues. ✌️

**Closed** 2023-10-10 08:11 UTC
